// Group
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const OPEN_GROUP_NAME_EDIT = 'OPEN_GROUP_NAME_EDIT';
export const CLOSE_GROUP_NAME_EDIT = 'CLOSE_GROUP_NAME_EDIT';
export const EDIT_GROUP_NAME = 'EDIT_GROUP_NAME';
export const OPEN_GROUP_MODAL = 'OPEN_GROUP_MODAL';
export const CLOSE_GROUP_MODAL = 'CLOSE_GROUP_MODAL';
// Tasks
export const ADD_TASK = 'ADD_TASK';
export const CHECK_TASK = 'CHECK_TASK';
export const DELETE_TASK = 'DELETE_TASK';
// Background
export const SELECT_BACKGROUND = 'SELECT_BACKGROUND';
export const OPEN_BACKGROUND_MODAL = 'OPEN_BACKGROUND_MODAL';
export const CLOSE_BACKGROUND_MODAL = 'CLOSE_BACKGROUND_MODAL';
